### ISSUE TITLE
Compile error in app.rb when creating single app pool and website

### ISSUE THREAD

**Issue by endakenny** [opscode-cookbooks/iis#95]
Hi Folks

My cookbook only contains a single recipe with the following content and a single change to the metadata.rb file to depend on the iis cookbook 3.0.0
-----------------------------------------------------------------
iis_pool "Atlas" do
    pool_name "Atlas"
    runtime_version '4.0'
    pipeline_mode :Integrated
    thirty_two_bit :false
    private_mem 2097152
    worker_idle_timeout '00:00:00'
    recycle_after_time '00:00:00'
    recycle_at_time '00:00:00'
    action [:add, :config, :start]
    retries 3
end

iis_site info[:website_name] do
    protocol :http
    port 80
    path website_dir
    application_pool "Atlas"
    host_header "atlassbx.hps.com"
    action [:add, :start]
    retries 3
end

-----------------------------------------------------------------

I'm using Chef 11.16.4 - its a hosted chef instance. 

Here were the cookbooks used 
[2014-12-22T10:41:29+00:00] INFO: Loading cookbooks [testing-new-iis-cookbook@0.1.0, iis@3.0.0, windows@1.36.1, chef_handler@1.1.6]
Synchronizing Cookbooks:

Here was the compile exception:
[2014-12-22T10:41:49+00:00] INFO: Storing updated cookbooks/chef_handler/README.md in the cache.

chef_handler Compiling Cookbooks...
Recipe Compile Error in C:/Users/kennye/.chef/local-mode-cache/cache/cookbooks/iis/providers/app.rb

TypeError

wrong argument type Class (expected Module)

Cookbook Trace:

C:/Users/kennye/.chef/local-mode-cache/cache/cookbooks/iis/providers/app.rb:26:in include' C:/Users/kennye/.chef/local-mode-cache/cache/cookbooks/iis/providers/app.rb:26:inclass_from_file'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/mixin/from_file.rb:42:in class_eval' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/mixin/from_file.rb:42:inclass_from_file'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/provider/lwrp_base.rb:94:in build_from_file' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:211:inload_lwrp_provider'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:202:in block in load_lwrps_from_cookbook ' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:201:ineach'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:201:in load_lwrps_from_cookbook' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:121:inblock in compile_lwrps'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:120:in each' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:120:incompile_lwrps'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:73:in compile' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/run_context.rb:88:inload'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/policy_builder/expand_node_object.rb:73:in setup_run_context' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/client.rb:265:insetup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/client.rb:429:in do_run' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/client.rb:227:inrun'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/application.rb:217:in run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/application/client.rb:328:inblock in run_application'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/application/client.rb:317:in loop' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/application/client.rb:317:inrun_application'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/application.rb:67:in run' C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/bin/chef-client:26:in'
C:/opscode/chef/bin/chef-client:23:in load' C:/opscode/chef/bin/chef-client:23:in'

Relevant File Content:

C:/Users/kennye/.chef/local-mode-cache/cache/cookbooks/iis/providers/app.rb:

19: # limitations under the License.
20: #
21:
22: require 'chef/mixin/shell_out'
23: require 'rexml/document'
24:
25: include Chef::Mixin::ShellOut
26>> include Opscode::IIS::Helper
27: include Windows::Helper
28: include REXML
29:
30: action :add do
31: unless @current_resource.exists
32: cmd = "#{appcmd} add app /site.name:\"#{@new_resource.app_name}\""
33: cmd << " /path:\"#{@new_resource.path}\""
34: cmd << " /applicationPool:\"#{@new_resource.application_pool}\"" if @new_resource.application_pool
35: cmd << " /physicalPath:\"#{win_friendly_path(@new_resource.physical_path)}\"" if @new_resource.physical_path

**Comment by endakenny** [comment]
@EasyAsABC123  - in my attempted to test you branch of the iis cookbook (https://github.com/EasyAsABC123/iis/tree/hotfix_helper-class) -  cannot upload it to my chef server. 
I get this error:

PS C:\chef> knife cookbook upload iis-hotfix_helper-class --cookbook-path PATH:C:\chef\cookbooks
ERROR: Could not find cookbook iis-hotfix_helper-class in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

I have verified that i am not doing anything silly in my config - knife.rb points to the correct cookbooks directory and that the directory of the correct name is present. I have also verified that i can upload other cookbooks(more than one.)

Furthermore when i test the uploading of the iis cookbook the code which verifies if there is another version of iis(of which your cookbook is kind of version) in the cookbooks directory can see the iis-hotfix_helper-class cookbook is present. See below

PS C:\chef> knife cookbook upload iis --cookbook-path PATH:C:\chef\cookbooks
WARNING: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
WARNING: The cookbooks: iis exist in multiple places in your cookbook_path.
A composite version of these cookbooks has been compiled for uploading.

IMPORTANT: In a future version of Chef, this behavior will be removed and you will no longer
be able to have the same version of a cookbook in multiple places in your cookbook_path.
WARNING: The affected cookbooks are located:
iis:
  C:/chef/cookbooks/iis
  C:/chef/cookbooks/iis-hotfix_helper-class
WARNING: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Uploading iis            [3.0.2]
Uploaded 1 cookbook.

**Comment by EasyAsABC123** [comment]
Simply run knife cookbook upload iis --force

We want to make sure it is the latest code

Justin Schuhmann

**Comment by christrotter** [comment]
I tried running the IIS hotfix branch you linked, was still getting 'cleanpath' errors.  Tried updating to chef-client 12.0.3-1, back to a ruby segfault that comes up just after loading cookbooks.  Sooo...

Anything I should be doing differently?  What other info can I provide to help?

**Comment by EasyAsABC123** [comment]
yeah the issue there is that you need chef-client > 12 for Chef::Util::PathHelper to work.  I’m about to could backwards compatibility.  it really isn’t that much code then you can test on chef-client 11.x.x
-- 
Justin Schuhmann

On January 2, 2015 at 9:14:52 AM, christrotter (notifications@github.com) wrote:

I tried running the IIS hotfix branch you linked, was still getting 'cleanpath' errors. Tried updating to chef-client 12.0.3-1, back to a ruby segfault that comes up just after loading cookbooks. Sooo...

Anything I should be doing differently? What other info can I provide to help?

**Comment by endakenny** [comment]
@EasyAsABC123  - im not trying to upload the iis cookbook - im uploading the iis-hotfix_helper-class. it appears there is an issue uploading this cookbook only. i get the same error when trying to to use the --force option:

PS C:\chef> knife cookbook upload iis-hotfix_helper-class --force
ERROR: Could not find cookbook iis-hotfix_helper-class in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

**Comment by EasyAsABC123** [comment]
rename that folder to iis, in the metabase file in that folder you’ll see the cookbook name is IIS.  this is what knife is looking at when you try to upload it.  That’s why you are getting the below error when trying to upload it.  
-- 
Justin Schuhmann

On January 2, 2015 at 9:25:42 AM, endakenny (notifications@github.com) wrote:

@EasyAsABC123 - im not trying to upload the iis cookbook - im uploading the iis-hotfix_helper-class. it appears there is an issue uploading this cookbook only. i get the same error when trying to to use the --force option:

PS C:\chef> knife cookbook upload iis-hotfix_helper-class --force
ERROR: Could not find cookbook iis-hotfix_helper-class in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

**Comment by EasyAsABC123** [comment]
@endakenny I just checked in the new backwards compatibility changes to that branch.  I'm testing them myself.  Initial test with chef-client 12 worked, i'll be testing chef-client 11.x.x now.

**Comment by EasyAsABC123** [comment]
new patch (3.0.3) worked in:
chef-client 
11.12.4-1
11.12.8-1
11.12.8-2
11.14.2-1(failed) NoMethodError: undefined method `cleanpath` new patch required to fix.
12.0.3-1
-- 
Justin Schuhmann

On January 2, 2015 at 9:27:09 AM, Justin Schuhmann (jmschu02@gmail.com) wrote:

rename that folder to iis, in the metabase file in that folder you’ll see the cookbook name is IIS.  this is what knife is looking at when you try to upload it.  That’s why you are getting the below error when trying to upload it.  
-- 
Justin Schuhmann

On January 2, 2015 at 9:25:42 AM, endakenny (notifications@github.com) wrote:

@EasyAsABC123 - im not trying to upload the iis cookbook - im uploading the iis-hotfix_helper-class. it appears there is an issue uploading this cookbook only. i get the same error when trying to to use the --force option:

PS C:\chef> knife cookbook upload iis-hotfix_helper-class --force
ERROR: Could not find cookbook iis-hotfix_helper-class in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

**Comment by EasyAsABC123** [comment]
@endakenny
new path (3.0.4) worked in:
11.12.4-1
11.12.8-1
11.12.8-2
11.14.2-1
12.0.3-1

So if you don’t mind grabbing the latest from https://github.com/EasyAsABC123/iis/tree/hotfix_helper-class and putting it in your iis folder to test.
-- 
Justin Schuhmann

On January 2, 2015 at 10:16:54 AM, Justin Schuhmann (jmschu02@gmail.com) wrote:

new patch (3.0.3) worked in:
chef-client 
11.12.4-1
11.12.8-1
11.12.8-2
11.14.2-1(failed) NoMethodError: undefined method `cleanpath` new patch required to fix.
12.0.3-1
-- 
Justin Schuhmann

On January 2, 2015 at 9:27:09 AM, Justin Schuhmann (jmschu02@gmail.com) wrote:

rename that folder to iis, in the metabase file in that folder you’ll see the cookbook name is IIS.  this is what knife is looking at when you try to upload it.  That’s why you are getting the below error when trying to upload it.  
-- 
Justin Schuhmann

On January 2, 2015 at 9:25:42 AM, endakenny (notifications@github.com) wrote:

@EasyAsABC123 - im not trying to upload the iis cookbook - im uploading the iis-hotfix_helper-class. it appears there is an issue uploading this cookbook only. i get the same error when trying to to use the --force option:

PS C:\chef> knife cookbook upload iis-hotfix_helper-class --force
ERROR: Could not find cookbook iis-hotfix_helper-class in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

**Comment by christrotter** [comment]
Hm, why only up to 11.14?  (latest available is 11.16.4-1 - still getting cleanpath errors with this)

I'll try 11.14 and update...

**Comment by EasyAsABC123** [comment]
@christrotter because I manually have to update each version to test.  I’ll update to 11.16.4-1 and see what happens.

3.0.4 worked on 11.16.4-1 for me

this is the tests i’m running:
```ruby
#
# Cookbook Name:: test-iis
# Recipe:: default
#
# Copyright 2014, YOUR_COMPANY_NAME
#
# All rights reserved - Do Not Redistribute
#

# stop and delete the default site
iis_site 'Default Web Site' do
  action [:stop, :delete]
end

directory "#{node['iis']['docroot']}testfu" do
  recursive true
  action :create
end

# creates a new app pool
iis_pool 'myAppPool_v1_1' do
  runtime_version "2.0"
  pipeline_mode :Classic
  action :add
end

# create and start a new site that maps to
# the physical location C:\inetpub\wwwroot\testfu
iis_site 'Testfu Site' do
  protocol :http
  port 80
  application_pool 'myAppPool_v1_1'
  path "#{node['iis']['docroot']}testfu"
  action [:add,:start]
end

 iis_pool "test" do
     runtime_version "4.0"
     pipeline_mode :Integrated
     action :add
 end

 iis_pool "test" do
     pool_username "username"
     pool_password "password"
     action :config
 end

 iis_pool "test" do
    action :recycle
 end
```

-- 
Justin Schuhmann

On January 2, 2015 at 10:32:25 AM, christrotter (notifications@github.com) wrote:

Hm, why only up to 11.14? (latest available is 11.16.4-1 - still getting cleanpath errors with this)

I'll try 11.14 and update...

**Comment by christrotter** [comment]
Aha, I had re-downloaded that branch...but didn't refresh the page so the zip was still 3.0.2.  Refreshed, downloaded 3.0.4, and no longer getting cleanpath errors (I've moved to chef-client 11.14).

I'll do more testing and let you know.

**Comment by EasyAsABC123** [comment]
@christrotter thanks, yeah with this type of development you'll see i apply new changes rapidly.  :) thanks again.

**Comment by christrotter** [comment]
I'd say things are working, except for the bindings are still broken (using your syntax).  I'll open a separate issue on that to keep things somewhat organized.

**Comment by EasyAsABC123** [comment]
@christrotter using `bindings "http/10.12.0.136:80:www.domain.com,https/*:443:www.domain.com"` it is still failing for you? i tested that...i think, basically it is `"protocol/ip address:port:domain,protocol/ip address:port:domain,protocol/ip address:port:domain"` list goes on comma separated.  feel free to post it in a separate issue and i'll work on it there.

**Comment by EasyAsABC123** [comment]
Appears to be resolved #96

**Comment by endakenny** [comment]
@EasyAsABC123 - I have made progress - thanks for your help. The cookbook works for me for a site and and app pool. Now im trying to use the iis_vdir resource which is the main reason im evaluating the new version of the iis cookbook. Im seeing odd behaviour where a resource will not work if the indentation is too many spaces (should i log a seperate issue for this?). That can be overcome by adjusting the indent. 
**For the iis_vdir resource - here is what i declared:**
Resource Declaration:
---------------------
# In C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-new-iis-cookbook/recipes/default.rb

 61: iis_vdir 'Testfu Site/' do
 62: action :add
 63: #application_name 'Testfu Site'
 64: path '/Content/Test'
 65: physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
 66: end
 67:

**Here is what is compiled:**
Compiled Resource:
------------------
# Declared in C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-new-iis-cookbook/recipes/default.rb:61:in `from_file'

iis_vdir("Testfu Site/") do
  action [:add]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :iis_vdir
  cookbook_name "testing-new-iis-cookbook"
  recipe_name "default"
  path "/Content/Test"
  physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
  application_name "Testfu Site/"
  logon_method :ClearText
  allow_sub_dir_config true
end

**Here is the appcmd comand that is run:**
Chef Client failed. 0 resources updated in 49.350937 seconds
[2015-01-02T16:38:15+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: iis_vdir[Testfu Site/] (testing-new-iis-cookbook::default line 61) had an error: Mixlib
::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42], but received '87'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe add vdir /app.name:"" /path:"/Content/Test" /physicalPath:"C:\inetpub\wwwroot\testfu\Content" /logon
Method:ClearText /allowSubDirConfig:true ----
STDOUT: ERROR ( message:Must specify the APP object with identifier. )



@EasyAsABC123 - so the 'application_name'- although it appears to correctly compile to it correct value gets converted to "" - an empty string before for the actuall appcmd command. Do you know what the issue is here?

**Comment by endakenny** [comment]
# For the iis_vdir resource - here is what i declared:
## Resource Declaration:
---------------------
### In C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-new-iis-cookbook/recipes/default.rb

 61: iis_vdir 'Testfu Site/' do
 62: action :add
 63: #application_name 'Testfu Site'
 64: path '/Content/Test'
 65: physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
 66: end
 67:

**Comment by EasyAsABC123** [comment]
Make sure to leave this issue open until the pull request is accepted.

You just removed the # in front of application name right? # are comments in ruby so you weren't passing an application name.  Perhaps I should validate that you pass something there.

Justin Schuhmann

**Comment by endakenny** [comment]
@EasyAsABC123  - yes i know that the application_name is commented out  - that is intentional - I tried to use this before i tried the above but i was getting an error to say it doesn't exist. Should i have expected that to work then? (i tried it but then figured the error was quite definitive)

# Resource in recipe:

    Resource Declaration:
    ---------------------
     In C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-new-iis-cookbook/recipes/default.rb

     61: iis_vdir 'Testfu Site/' do
     62: action :add
     63: application_name 'Testfu Site'
     64: path '/Content/Test'
     65: physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
     66: end
     67:

# Compiled Resource:
    ------------------
    Declared in C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-new-iis-cookbook/recipes/default.rb:61:in `from_file'

    iis_vdir("Testfu Site/") do
      action [:add]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :iis_vdir
      cookbook_name "testing-new-iis-cookbook"
      recipe_name "default"
      application_name "Testfu Site"
      path "/Content/Test"
      physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
    end

[2015-01-02T16:34:02+00:00] INFO: Running queued delayed notifications before re-raising exception

# Error was:
[2015-01-02T16:34:02+00:00] FATAL: NoMethodError: iis_vdir[Testfu Site/] (testing-new-iis-cookbook::default line 61) had an error: NoMethodError: undefined meth
od `application_name=' for Chef::Resource::IisVdir

**Comment by EasyAsABC123** [comment]
@endakenny grab iis@3.0.7 from the hotfix branch, it fixes this issue

as a sidenote this is the iis_vdir definition (i updated readme)

```
iis_vdir 'Testfu Site/' do
   action :add
   application_name 'Testfu Site/'
   path '/Content/Test'
   physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
 end
```

**Comment by endakenny** [comment]
Thanks - im trying that now. About the indentation issues
# Issue
Im seeing odd behaviour where a resource will not work if the indentation is too many spaces 

shall i open a new issue for it?

**Comment by EasyAsABC123** [comment]
@endakenny can you provide an example?  I don't exactly understand what you mean, there is nothing unique about iis and indentation.  Is this a chef issue?

**Comment by endakenny** [comment]
@EasyAsABC123  - excellent , thank you.  Now i can create virtual directories. Im not to clear on whats differnt from what i did(posted above) Does the iis_vdir value('Testfu Site/') have to be the same as the application_name value('Testfu Site/') for it work?

**Comment by endakenny** [comment]
@EasyAsABC123. The basic functionality is now working for me, i can create sites, app pools and virtual directories (Hallelujah!). Forget about the indentation - i was having a nightmare on Friday and attributed some errors to indentation. Everything works now with iis branch 3.0.7. Thanks for your help. Now i need to check it for compatibility with my large cookbook that uses iis and then i can add the a number of iis_vdir resources to it.

**Comment by EasyAsABC123** [comment]
No you don't have to pass application_name if you are passing it in the top as the `name` attribute.

Sorry for that confusion, it should work the same either way.

**Comment by EasyAsABC123** [comment]
@endakenny  sounds good let me know if another issue occurs
